// Generates _locales/<lang>/messages.json for every language below.
// Edit the tables, then run:  node tools/build-locales.mjs
// _locales/ is shipped in the extension (committed, not gitignored).
//
// Messages produced per language:
//   appName (brand), appDesc, UI[*], sc_<id> (shortcut labels),
//   cmd_block_* (command descriptions composed from blockPrefix + label + combo)
import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const BRAND = "Shortcut Blocker";

// Fixed combos for the manifest commands, and which label each one reuses.
const COMBOS = {
  "block-nav-back": "Alt+←", "block-nav-forward": "Alt+→", "block-nav-reload": "Ctrl+R",
  "block-nav-hard-reload": "Ctrl+Shift+R", "block-nav-home": "Alt+Home",
  "block-tab-new": "Ctrl+T", "block-tab-close": "Ctrl+W", "block-tab-reopen": "Ctrl+Shift+T",
  "block-tab-1": "Ctrl+1", "block-tab-9": "Ctrl+9", "block-tab-newwindow": "Ctrl+N",
  "block-tab-incognito": "Ctrl+Shift+N", "block-dev-tools2": "Ctrl+Shift+I",
  "block-dev-console": "Ctrl+Shift+J", "block-dev-source": "Ctrl+U", "block-dev-inspect": "Ctrl+Shift+C",
};
const CMD2LABEL = {
  "block-nav-back": "nav_back", "block-nav-forward": "nav_forward", "block-nav-reload": "nav_reload",
  "block-nav-hard-reload": "nav_hard_reload", "block-nav-home": "nav_home",
  "block-tab-new": "tab_new", "block-tab-close": "tab_close", "block-tab-reopen": "tab_reopen",
  "block-tab-1": "tab_1", "block-tab-9": "tab_9", "block-tab-newwindow": "tab_newwindow",
  "block-tab-incognito": "tab_incognito", "block-dev-tools2": "dev_tools2",
  "block-dev-console": "dev_console", "block-dev-source": "dev_source", "block-dev-inspect": "dev_inspect",
};
const blockPrefix = {
  en: "Block", ja: "ブロック", es: "Bloquear", pt_BR: "Bloquear", fr: "Bloquer",
  de: "Blockieren", it: "Blocca", ru: "Блокировать", zh_CN: "屏蔽", zh_TW: "封鎖", ko: "차단",
};

const LABELS = {
  en: { nav_back: "Back", nav_forward: "Forward", nav_reload: "Reload page", nav_hard_reload: "Hard reload (clear cache)", nav_home: "Home page", nav_stop: "Stop loading", nav_scrolldown: "Page down", nav_scrollup: "Page up", nav_top: "Top of page", nav_bottom: "Bottom of page", edit_copy: "Copy", edit_cut: "Cut", edit_paste: "Paste", edit_undo: "Undo", edit_redo: "Redo", edit_selectall: "Select all", edit_find: "Find", edit_findnext: "Find next", edit_save: "Save page", edit_print: "Print", tab_new: "New tab", tab_close: "Close tab", tab_reopen: "Reopen closed tab", tab_next: "Next tab", tab_prev: "Previous tab", tab_1: "Go to tab 1", tab_9: "Go to last tab", tab_newwindow: "New window", tab_incognito: "Incognito window", dev_tools: "Developer tools", dev_tools2: "Developer tools", dev_console: "Console", dev_source: "View source", dev_inspect: "Inspect element" },
  ja: { nav_back: "戻る", nav_forward: "進む", nav_reload: "ページ再読み込み", nav_hard_reload: "キャッシュクリア再読み込み", nav_home: "ホームページ", nav_stop: "読み込み中止", nav_scrolldown: "ページダウン", nav_scrollup: "ページアップ", nav_top: "ページ先頭", nav_bottom: "ページ末尾", edit_copy: "コピー", edit_cut: "切り取り", edit_paste: "貼り付け", edit_undo: "元に戻す", edit_redo: "やり直し", edit_selectall: "全選択", edit_find: "検索", edit_findnext: "次を検索", edit_save: "ページ保存", edit_print: "印刷", tab_new: "新しいタブ", tab_close: "タブを閉じる", tab_reopen: "閉じたタブを開く", tab_next: "次のタブ", tab_prev: "前のタブ", tab_1: "タブ1に移動", tab_9: "最後のタブに移動", tab_newwindow: "新しいウィンドウ", tab_incognito: "シークレットウィンドウ", dev_tools: "デベロッパーツール", dev_tools2: "デベロッパーツール", dev_console: "コンソール", dev_source: "ソース表示", dev_inspect: "要素の検証" },
  es: { nav_back: "Atrás", nav_forward: "Adelante", nav_reload: "Recargar página", nav_hard_reload: "Recarga forzada (borrar caché)", nav_home: "Página de inicio", nav_stop: "Detener carga", nav_scrolldown: "Avanzar página", nav_scrollup: "Retroceder página", nav_top: "Inicio de la página", nav_bottom: "Final de la página", edit_copy: "Copiar", edit_cut: "Cortar", edit_paste: "Pegar", edit_undo: "Deshacer", edit_redo: "Rehacer", edit_selectall: "Seleccionar todo", edit_find: "Buscar", edit_findnext: "Buscar siguiente", edit_save: "Guardar página", edit_print: "Imprimir", tab_new: "Nueva pestaña", tab_close: "Cerrar pestaña", tab_reopen: "Reabrir pestaña cerrada", tab_next: "Pestaña siguiente", tab_prev: "Pestaña anterior", tab_1: "Ir a la pestaña 1", tab_9: "Ir a la última pestaña", tab_newwindow: "Nueva ventana", tab_incognito: "Ventana de incógnito", dev_tools: "Herramientas para desarrolladores", dev_tools2: "Herramientas para desarrolladores", dev_console: "Consola", dev_source: "Ver código fuente", dev_inspect: "Inspeccionar elemento" },
  pt_BR: { nav_back: "Voltar", nav_forward: "Avançar", nav_reload: "Recarregar página", nav_hard_reload: "Recarga forçada (limpar cache)", nav_home: "Página inicial", nav_stop: "Parar carregamento", nav_scrolldown: "Página abaixo", nav_scrollup: "Página acima", nav_top: "Início da página", nav_bottom: "Fim da página", edit_copy: "Copiar", edit_cut: "Recortar", edit_paste: "Colar", edit_undo: "Desfazer", edit_redo: "Refazer", edit_selectall: "Selecionar tudo", edit_find: "Localizar", edit_findnext: "Localizar próxima", edit_save: "Salvar página", edit_print: "Imprimir", tab_new: "Nova aba", tab_close: "Fechar aba", tab_reopen: "Reabrir aba fechada", tab_next: "Próxima aba", tab_prev: "Aba anterior", tab_1: "Ir para a aba 1", tab_9: "Ir para a última aba", tab_newwindow: "Nova janela", tab_incognito: "Janela anônima", dev_tools: "Ferramentas do desenvolvedor", dev_tools2: "Ferramentas do desenvolvedor", dev_console: "Console", dev_source: "Ver código-fonte", dev_inspect: "Inspecionar elemento" },
  fr: { nav_back: "Précédent", nav_forward: "Suivant", nav_reload: "Recharger la page", nav_hard_reload: "Rechargement forcé (vider le cache)", nav_home: "Page d'accueil", nav_stop: "Arrêter le chargement", nav_scrolldown: "Page suivante", nav_scrollup: "Page précédente", nav_top: "Haut de la page", nav_bottom: "Bas de la page", edit_copy: "Copier", edit_cut: "Couper", edit_paste: "Coller", edit_undo: "Annuler", edit_redo: "Rétablir", edit_selectall: "Tout sélectionner", edit_find: "Rechercher", edit_findnext: "Rechercher le suivant", edit_save: "Enregistrer la page", edit_print: "Imprimer", tab_new: "Nouvel onglet", tab_close: "Fermer l'onglet", tab_reopen: "Rouvrir l'onglet fermé", tab_next: "Onglet suivant", tab_prev: "Onglet précédent", tab_1: "Aller à l'onglet 1", tab_9: "Aller au dernier onglet", tab_newwindow: "Nouvelle fenêtre", tab_incognito: "Fenêtre de navigation privée", dev_tools: "Outils de développement", dev_tools2: "Outils de développement", dev_console: "Console", dev_source: "Afficher la source", dev_inspect: "Inspecter l'élément" },
  de: { nav_back: "Zurück", nav_forward: "Vorwärts", nav_reload: "Seite neu laden", nav_hard_reload: "Neu laden (Cache leeren)", nav_home: "Startseite", nav_stop: "Laden beenden", nav_scrolldown: "Seite nach unten", nav_scrollup: "Seite nach oben", nav_top: "Seitenanfang", nav_bottom: "Seitenende", edit_copy: "Kopieren", edit_cut: "Ausschneiden", edit_paste: "Einfügen", edit_undo: "Rückgängig", edit_redo: "Wiederholen", edit_selectall: "Alles auswählen", edit_find: "Suchen", edit_findnext: "Weitersuchen", edit_save: "Seite speichern", edit_print: "Drucken", tab_new: "Neuer Tab", tab_close: "Tab schließen", tab_reopen: "Geschlossenen Tab öffnen", tab_next: "Nächster Tab", tab_prev: "Vorheriger Tab", tab_1: "Zu Tab 1 wechseln", tab_9: "Zum letzten Tab", tab_newwindow: "Neues Fenster", tab_incognito: "Inkognitofenster", dev_tools: "Entwicklertools", dev_tools2: "Entwicklertools", dev_console: "Konsole", dev_source: "Quelltext anzeigen", dev_inspect: "Element untersuchen" },
  it: { nav_back: "Indietro", nav_forward: "Avanti", nav_reload: "Ricarica pagina", nav_hard_reload: "Ricarica forzata (svuota cache)", nav_home: "Pagina iniziale", nav_stop: "Interrompi caricamento", nav_scrolldown: "Pagina giù", nav_scrollup: "Pagina su", nav_top: "Inizio pagina", nav_bottom: "Fine pagina", edit_copy: "Copia", edit_cut: "Taglia", edit_paste: "Incolla", edit_undo: "Annulla", edit_redo: "Ripeti", edit_selectall: "Seleziona tutto", edit_find: "Trova", edit_findnext: "Trova successivo", edit_save: "Salva pagina", edit_print: "Stampa", tab_new: "Nuova scheda", tab_close: "Chiudi scheda", tab_reopen: "Riapri scheda chiusa", tab_next: "Scheda successiva", tab_prev: "Scheda precedente", tab_1: "Vai alla scheda 1", tab_9: "Vai all'ultima scheda", tab_newwindow: "Nuova finestra", tab_incognito: "Finestra di navigazione in incognito", dev_tools: "Strumenti per sviluppatori", dev_tools2: "Strumenti per sviluppatori", dev_console: "Console", dev_source: "Visualizza sorgente", dev_inspect: "Ispeziona elemento" },
  ru: { nav_back: "Назад", nav_forward: "Вперёд", nav_reload: "Обновить страницу", nav_hard_reload: "Полная перезагрузка (очистить кэш)", nav_home: "Домашняя страница", nav_stop: "Остановить загрузку", nav_scrolldown: "На страницу вниз", nav_scrollup: "На страницу вверх", nav_top: "В начало страницы", nav_bottom: "В конец страницы", edit_copy: "Копировать", edit_cut: "Вырезать", edit_paste: "Вставить", edit_undo: "Отменить", edit_redo: "Повторить", edit_selectall: "Выделить всё", edit_find: "Найти", edit_findnext: "Найти далее", edit_save: "Сохранить страницу", edit_print: "Печать", tab_new: "Новая вкладка", tab_close: "Закрыть вкладку", tab_reopen: "Открыть закрытую вкладку", tab_next: "Следующая вкладка", tab_prev: "Предыдущая вкладка", tab_1: "Перейти к вкладке 1", tab_9: "Перейти к последней вкладке", tab_newwindow: "Новое окно", tab_incognito: "Окно инкогнито", dev_tools: "Инструменты разработчика", dev_tools2: "Инструменты разработчика", dev_console: "Консоль", dev_source: "Посмотреть код страницы", dev_inspect: "Просмотреть элемент" },
  zh_CN: { nav_back: "后退", nav_forward: "前进", nav_reload: "重新加载页面", nav_hard_reload: "强制重新加载（清除缓存）", nav_home: "主页", nav_stop: "停止加载", nav_scrolldown: "向下翻页", nav_scrollup: "向上翻页", nav_top: "页首", nav_bottom: "页尾", edit_copy: "复制", edit_cut: "剪切", edit_paste: "粘贴", edit_undo: "撤销", edit_redo: "重做", edit_selectall: "全选", edit_find: "查找", edit_findnext: "查找下一个", edit_save: "保存页面", edit_print: "打印", tab_new: "新建标签页", tab_close: "关闭标签页", tab_reopen: "重新打开已关闭标签页", tab_next: "下一个标签页", tab_prev: "上一个标签页", tab_1: "切换到标签页 1", tab_9: "切换到最后一个标签页", tab_newwindow: "新建窗口", tab_incognito: "无痕窗口", dev_tools: "开发者工具", dev_tools2: "开发者工具", dev_console: "控制台", dev_source: "查看源代码", dev_inspect: "检查元素" },
  zh_TW: { nav_back: "上一頁", nav_forward: "下一頁", nav_reload: "重新整理頁面", nav_hard_reload: "強制重新整理（清除快取）", nav_home: "首頁", nav_stop: "停止載入", nav_scrolldown: "向下捲動一頁", nav_scrollup: "向上捲動一頁", nav_top: "頁面頂端", nav_bottom: "頁面底端", edit_copy: "複製", edit_cut: "剪下", edit_paste: "貼上", edit_undo: "復原", edit_redo: "重做", edit_selectall: "全選", edit_find: "尋找", edit_findnext: "尋找下一個", edit_save: "儲存頁面", edit_print: "列印", tab_new: "新增分頁", tab_close: "關閉分頁", tab_reopen: "重新開啟已關閉分頁", tab_next: "下一個分頁", tab_prev: "上一個分頁", tab_1: "切換到分頁 1", tab_9: "切換到最後一個分頁", tab_newwindow: "新增視窗", tab_incognito: "無痕視窗", dev_tools: "開發人員工具", dev_tools2: "開發人員工具", dev_console: "主控台", dev_source: "檢視原始碼", dev_inspect: "檢查元素" },
  ko: { nav_back: "뒤로", nav_forward: "앞으로", nav_reload: "페이지 새로고침", nav_hard_reload: "강력 새로고침(캐시 지우기)", nav_home: "홈페이지", nav_stop: "로드 중지", nav_scrolldown: "페이지 다운", nav_scrollup: "페이지 업", nav_top: "페이지 맨 위", nav_bottom: "페이지 맨 아래", edit_copy: "복사", edit_cut: "잘라내기", edit_paste: "붙여넣기", edit_undo: "실행취소", edit_redo: "다시실행", edit_selectall: "모두 선택", edit_find: "찾기", edit_findnext: "다음 찾기", edit_save: "페이지 저장", edit_print: "인쇄", tab_new: "새 탭", tab_close: "탭 닫기", tab_reopen: "닫은 탭 다시 열기", tab_next: "다음 탭", tab_prev: "이전 탭", tab_1: "탭 1로 이동", tab_9: "마지막 탭으로 이동", tab_newwindow: "새 창", tab_incognito: "시크릿 창", dev_tools: "개발자 도구", dev_tools2: "개발자 도구", dev_console: "콘솔", dev_source: "소스 보기", dev_inspect: "요소 검사" },
};

const UI = {
  en: { appDesc: "Turn individual keyboard shortcuts on or off while browsing — block accidental Ctrl+W, Backspace navigation, F12, and more.", openShortcutsTitle: "Open Chrome's keyboard shortcuts page", toggleTheme: "Toggle theme", searchTitle: "Search", capturePlaceholder: "e.g. Ctrl + K (you can type it)", captureTitle: "Press keys to record", record: "Record", recording: "Recording…", labelPlaceholder: "Label (optional)", add: "Add", cancel: "Cancel", catAll: "All", catNav: "Nav", catEdit: "Edit", catTab: "Tabs", catDev: "Dev", catCustom: "Custom", searchPlaceholder: "Search shortcuts", searchAddPlaceholder: "Search / add (e.g. Ctrl+K)", guideTitle: "How to register a shortcut", guideStep1: "Click \"Open settings page\" below", guideStep2: "Find \"Shortcut Blocker\" in the list", guideStep4: "Press the keys to record them", guideRowDefault: "Click the input box for the target row", guideNote: "Once registered, the key is bound to a do-nothing command and disabled.", openSettingsPage: "Open settings page", close: "Close", guideTargetFmt: "Target: $label$ ($combo$)", guideRowFmt: "Click the input box for the \"Block: $row$\" row", bulkLabel: "This tab:", disableAll: "Disable all", enableAll: "Enable all", addCustom: "+ Add custom shortcut", disableFmt: "Disable $name$", noteCommand: "Register from the keyboard shortcuts page on the right", noteUnblockable: "Can't be blocked (browser restriction)", gearTitle: "Register on Chrome's shortcuts page", lockTitle: "Can't be blocked (browser restriction)", delete: "Delete", statusDisabled: "$count$ shortcut(s) disabled", statusAllEnabled: "All shortcuts enabled", showReserved: "Show browser-reserved shortcuts" },
  ja: { appDesc: "ブラウジング中のキーボードショートカットを個別にオン/オフ。誤操作の Ctrl+W、Backspace での戻る、F12 などをブロックできます。", openShortcutsTitle: "Chrome のショートカット設定を開く", toggleTheme: "テーマ切替", searchTitle: "検索", capturePlaceholder: "例: Ctrl + K（直接入力可）", captureTitle: "キーを押して記録", record: "記録", recording: "記録中…", labelPlaceholder: "ラベル (任意)", add: "追加", cancel: "キャンセル", catAll: "全て", catNav: "ナビ", catEdit: "編集", catTab: "タブ", catDev: "開発", catCustom: "カスタム", searchPlaceholder: "ショートカットを検索", searchAddPlaceholder: "検索 / 追加（例: Ctrl+K）", guideTitle: "ショートカット登録の手順", guideStep1: "下の「設定ページを開く」を押す", guideStep2: "一覧から「Shortcut Blocker」を探す", guideStep4: "キーを実際に押して記録する", guideRowDefault: "対象の欄の入力ボックスをクリック", guideNote: "登録すると、そのキーは何もしないコマンドに割り当てられ無効化されます。", openSettingsPage: "設定ページを開く", close: "閉じる", guideTargetFmt: "対象: $label$（$combo$）", guideRowFmt: "一覧の「ブロック: $row$」の入力ボックスをクリック", bulkLabel: "このタブを", disableAll: "すべて無効化", enableAll: "すべて有効化", addCustom: "＋ カスタムショートカットを追加", disableFmt: "$name$ を無効化", noteCommand: "右のキーボードショートカットの設定から登録", noteUnblockable: "ブラウザ制約によりブロック不可", gearTitle: "Chrome のショートカット設定で登録", lockTitle: "ブラウザ制約によりブロックできません", delete: "削除", statusDisabled: "$count$個のショートカットが無効", statusAllEnabled: "全てのショートカットが有効", showReserved: "ブラウザ予約ショートカットを表示" },
  es: { appDesc: "Activa o desactiva atajos de teclado individuales al navegar: bloquea Ctrl+W accidentales, la navegación con Retroceso, F12 y más.", openShortcutsTitle: "Abrir la página de atajos de teclado de Chrome", toggleTheme: "Cambiar tema", searchTitle: "Buscar", capturePlaceholder: "ej.: Ctrl + K (puedes escribirlo)", captureTitle: "Pulsa las teclas para grabar", record: "Grabar", recording: "Grabando…", labelPlaceholder: "Etiqueta (opcional)", add: "Añadir", cancel: "Cancelar", catAll: "Todos", catNav: "Naveg.", catEdit: "Editar", catTab: "Pestañas", catDev: "Dev", catCustom: "Personal.", searchPlaceholder: "Buscar atajos", searchAddPlaceholder: "Buscar / añadir (ej.: Ctrl+K)", guideTitle: "Cómo registrar un atajo", guideStep1: "Pulsa \"Abrir página de ajustes\" abajo", guideStep2: "Busca \"Shortcut Blocker\" en la lista", guideStep4: "Pulsa las teclas para grabarlas", guideRowDefault: "Haz clic en el cuadro de la fila correspondiente", guideNote: "Una vez registrada, la tecla se asigna a un comando vacío y queda desactivada.", openSettingsPage: "Abrir página de ajustes", close: "Cerrar", guideTargetFmt: "Objetivo: $label$ ($combo$)", guideRowFmt: "Haz clic en el cuadro de la fila \"Bloquear: $row$\"", bulkLabel: "Esta pestaña:", disableAll: "Desactivar todo", enableAll: "Activar todo", addCustom: "+ Añadir atajo personalizado", disableFmt: "Desactivar $name$", noteCommand: "Regístralo desde la página de atajos de teclado a la derecha", noteUnblockable: "No se puede bloquear (restricción del navegador)", gearTitle: "Registrar en la página de atajos de Chrome", lockTitle: "No se puede bloquear (restricción del navegador)", delete: "Eliminar", statusDisabled: "$count$ atajo(s) desactivado(s)", statusAllEnabled: "Todos los atajos activados", showReserved: "Mostrar atajos reservados del navegador" },
  pt_BR: { appDesc: "Ative ou desative atalhos de teclado individuais ao navegar — bloqueie Ctrl+W acidental, navegação com Backspace, F12 e mais.", openShortcutsTitle: "Abrir a página de atalhos de teclado do Chrome", toggleTheme: "Alternar tema", searchTitle: "Pesquisar", capturePlaceholder: "ex.: Ctrl + K (pode digitar)", captureTitle: "Pressione as teclas para gravar", record: "Gravar", recording: "Gravando…", labelPlaceholder: "Rótulo (opcional)", add: "Adicionar", cancel: "Cancelar", catAll: "Todos", catNav: "Naveg.", catEdit: "Editar", catTab: "Abas", catDev: "Dev", catCustom: "Personal.", searchPlaceholder: "Pesquisar atalhos", searchAddPlaceholder: "Pesquisar / adicionar (ex.: Ctrl+K)", guideTitle: "Como registrar um atalho", guideStep1: "Clique em \"Abrir página de configurações\" abaixo", guideStep2: "Encontre \"Shortcut Blocker\" na lista", guideStep4: "Pressione as teclas para gravá-las", guideRowDefault: "Clique na caixa de entrada da linha correspondente", guideNote: "Uma vez registrada, a tecla é vinculada a um comando vazio e desativada.", openSettingsPage: "Abrir página de configurações", close: "Fechar", guideTargetFmt: "Alvo: $label$ ($combo$)", guideRowFmt: "Clique na caixa de entrada da linha \"Bloquear: $row$\"", bulkLabel: "Esta aba:", disableAll: "Desativar tudo", enableAll: "Ativar tudo", addCustom: "+ Adicionar atalho personalizado", disableFmt: "Desativar $name$", noteCommand: "Registre na página de atalhos de teclado à direita", noteUnblockable: "Não pode ser bloqueado (restrição do navegador)", gearTitle: "Registrar na página de atalhos do Chrome", lockTitle: "Não pode ser bloqueado (restrição do navegador)", delete: "Excluir", statusDisabled: "$count$ atalho(s) desativado(s)", statusAllEnabled: "Todos os atalhos ativados", showReserved: "Mostrar atalhos reservados do navegador" },
  fr: { appDesc: "Activez ou désactivez des raccourcis clavier individuels — bloquez les Ctrl+W accidentels, la navigation par Retour arrière, F12, etc.", openShortcutsTitle: "Ouvrir la page des raccourcis clavier de Chrome", toggleTheme: "Changer de thème", searchTitle: "Rechercher", capturePlaceholder: "ex. : Ctrl + K (saisie possible)", captureTitle: "Appuyez sur les touches pour enregistrer", record: "Enregistrer", recording: "Enregistrement…", labelPlaceholder: "Libellé (facultatif)", add: "Ajouter", cancel: "Annuler", catAll: "Tous", catNav: "Nav.", catEdit: "Édition", catTab: "Onglets", catDev: "Dév", catCustom: "Perso", searchPlaceholder: "Rechercher des raccourcis", searchAddPlaceholder: "Rechercher / ajouter (ex. : Ctrl+K)", guideTitle: "Comment enregistrer un raccourci", guideStep1: "Cliquez sur « Ouvrir la page des paramètres » ci-dessous", guideStep2: "Trouvez « Shortcut Blocker » dans la liste", guideStep4: "Appuyez sur les touches pour les enregistrer", guideRowDefault: "Cliquez dans le champ de la ligne concernée", guideNote: "Une fois enregistrée, la touche est associée à une commande sans effet et désactivée.", openSettingsPage: "Ouvrir la page des paramètres", close: "Fermer", guideTargetFmt: "Cible : $label$ ($combo$)", guideRowFmt: "Cliquez dans le champ de la ligne « Bloquer : $row$ »", bulkLabel: "Cet onglet :", disableAll: "Tout désactiver", enableAll: "Tout activer", addCustom: "+ Ajouter un raccourci personnalisé", disableFmt: "Désactiver $name$", noteCommand: "Enregistrez depuis la page des raccourcis clavier à droite", noteUnblockable: "Impossible à bloquer (restriction du navigateur)", gearTitle: "Enregistrer sur la page des raccourcis de Chrome", lockTitle: "Impossible à bloquer (restriction du navigateur)", delete: "Supprimer", statusDisabled: "$count$ raccourci(s) désactivé(s)", statusAllEnabled: "Tous les raccourcis activés", showReserved: "Afficher les raccourcis réservés au navigateur" },
  de: { appDesc: "Aktiviere oder deaktiviere einzelne Tastenkürzel beim Surfen — blockiere versehentliches Strg+W, Rücktaste-Navigation, F12 und mehr.", openShortcutsTitle: "Chrome-Tastenkürzelseite öffnen", toggleTheme: "Design wechseln", searchTitle: "Suchen", capturePlaceholder: "z. B. Strg + K (Eingabe möglich)", captureTitle: "Tasten drücken zum Aufzeichnen", record: "Aufzeichnen", recording: "Aufzeichnung…", labelPlaceholder: "Bezeichnung (optional)", add: "Hinzufügen", cancel: "Abbrechen", catAll: "Alle", catNav: "Nav.", catEdit: "Bearb.", catTab: "Tabs", catDev: "Dev", catCustom: "Eigene", searchPlaceholder: "Tastenkürzel suchen", searchAddPlaceholder: "Suchen / hinzufügen (z. B. Strg+K)", guideTitle: "Tastenkürzel registrieren", guideStep1: "Klicke unten auf „Einstellungsseite öffnen“", guideStep2: "Finde „Shortcut Blocker“ in der Liste", guideStep4: "Drücke die Tasten zum Aufzeichnen", guideRowDefault: "Klicke in das Eingabefeld der betreffenden Zeile", guideNote: "Nach der Registrierung wird die Taste einem leeren Befehl zugewiesen und deaktiviert.", openSettingsPage: "Einstellungsseite öffnen", close: "Schließen", guideTargetFmt: "Ziel: $label$ ($combo$)", guideRowFmt: "Klicke in das Eingabefeld der Zeile „Blockieren: $row$“", bulkLabel: "Dieser Tab:", disableAll: "Alle deaktivieren", enableAll: "Alle aktivieren", addCustom: "+ Eigenes Tastenkürzel hinzufügen", disableFmt: "$name$ deaktivieren", noteCommand: "Über die Tastenkürzelseite rechts registrieren", noteUnblockable: "Kann nicht blockiert werden (Browser-Einschränkung)", gearTitle: "Auf Chrome-Tastenkürzelseite registrieren", lockTitle: "Kann nicht blockiert werden (Browser-Einschränkung)", delete: "Löschen", statusDisabled: "$count$ Tastenkürzel deaktiviert", statusAllEnabled: "Alle Tastenkürzel aktiviert", showReserved: "Browserreservierte Tastenkürzel anzeigen" },
  it: { appDesc: "Attiva o disattiva singole scorciatoie da tastiera durante la navigazione: blocca Ctrl+W accidentali, navigazione con Backspace, F12 e altro.", openShortcutsTitle: "Apri la pagina delle scorciatoie da tastiera di Chrome", toggleTheme: "Cambia tema", searchTitle: "Cerca", capturePlaceholder: "es. Ctrl + K (puoi digitarlo)", captureTitle: "Premi i tasti per registrare", record: "Registra", recording: "Registrazione…", labelPlaceholder: "Etichetta (facoltativa)", add: "Aggiungi", cancel: "Annulla", catAll: "Tutte", catNav: "Nav.", catEdit: "Modifica", catTab: "Schede", catDev: "Dev", catCustom: "Person.", searchPlaceholder: "Cerca scorciatoie", searchAddPlaceholder: "Cerca / aggiungi (es. Ctrl+K)", guideTitle: "Come registrare una scorciatoia", guideStep1: "Fai clic su \"Apri pagina impostazioni\" in basso", guideStep2: "Trova \"Shortcut Blocker\" nell'elenco", guideStep4: "Premi i tasti per registrarli", guideRowDefault: "Fai clic nella casella della riga interessata", guideNote: "Una volta registrato, il tasto viene associato a un comando vuoto e disattivato.", openSettingsPage: "Apri pagina impostazioni", close: "Chiudi", guideTargetFmt: "Destinazione: $label$ ($combo$)", guideRowFmt: "Fai clic nella casella della riga \"Blocca: $row$\"", bulkLabel: "Questa scheda:", disableAll: "Disattiva tutto", enableAll: "Attiva tutto", addCustom: "+ Aggiungi scorciatoia personalizzata", disableFmt: "Disattiva $name$", noteCommand: "Registra dalla pagina delle scorciatoie da tastiera a destra", noteUnblockable: "Non bloccabile (limitazione del browser)", gearTitle: "Registra sulla pagina delle scorciatoie di Chrome", lockTitle: "Non bloccabile (limitazione del browser)", delete: "Elimina", statusDisabled: "$count$ scorciatoia/e disattivata/e", statusAllEnabled: "Tutte le scorciatoie attivate", showReserved: "Mostra scorciatoie riservate al browser" },
  ru: { appDesc: "Включайте и отключайте отдельные сочетания клавиш при просмотре — блокируйте случайное Ctrl+W, навигацию по Backspace, F12 и другое.", openShortcutsTitle: "Открыть страницу сочетаний клавиш Chrome", toggleTheme: "Сменить тему", searchTitle: "Поиск", capturePlaceholder: "напр. Ctrl + K (можно ввести)", captureTitle: "Нажмите клавиши для записи", record: "Запись", recording: "Запись…", labelPlaceholder: "Название (необязательно)", add: "Добавить", cancel: "Отмена", catAll: "Все", catNav: "Навиг.", catEdit: "Правка", catTab: "Вкладки", catDev: "Разраб.", catCustom: "Свои", searchPlaceholder: "Поиск сочетаний", searchAddPlaceholder: "Поиск / добавить (напр. Ctrl+K)", guideTitle: "Как зарегистрировать сочетание", guideStep1: "Нажмите «Открыть страницу настроек» ниже", guideStep2: "Найдите «Shortcut Blocker» в списке", guideStep4: "Нажмите клавиши для записи", guideRowDefault: "Щёлкните поле ввода в нужной строке", guideNote: "После регистрации клавиша назначается пустой команде и отключается.", openSettingsPage: "Открыть страницу настроек", close: "Закрыть", guideTargetFmt: "Цель: $label$ ($combo$)", guideRowFmt: "Щёлкните поле ввода в строке «Блокировать: $row$»", bulkLabel: "Эта вкладка:", disableAll: "Отключить все", enableAll: "Включить все", addCustom: "+ Добавить своё сочетание", disableFmt: "Отключить $name$", noteCommand: "Зарегистрируйте на странице сочетаний клавиш справа", noteUnblockable: "Невозможно заблокировать (ограничение браузера)", gearTitle: "Зарегистрировать на странице сочетаний Chrome", lockTitle: "Невозможно заблокировать (ограничение браузера)", delete: "Удалить", statusDisabled: "Отключено сочетаний: $count$", statusAllEnabled: "Все сочетания включены", showReserved: "Показывать зарезервированные браузером сочетания" },
  zh_CN: { appDesc: "浏览时逐个开启或关闭键盘快捷键——屏蔽误触的 Ctrl+W、退格键导航、F12 等。", openShortcutsTitle: "打开 Chrome 的键盘快捷键页面", toggleTheme: "切换主题", searchTitle: "搜索", capturePlaceholder: "例如 Ctrl + K（可直接输入）", captureTitle: "按下按键以记录", record: "记录", recording: "记录中…", labelPlaceholder: "标签（可选）", add: "添加", cancel: "取消", catAll: "全部", catNav: "导航", catEdit: "编辑", catTab: "标签页", catDev: "开发", catCustom: "自定义", searchPlaceholder: "搜索快捷键", searchAddPlaceholder: "搜索 / 添加（例如 Ctrl+K）", guideTitle: "如何注册快捷键", guideStep1: "点击下方的“打开设置页面”", guideStep2: "在列表中找到“Shortcut Blocker”", guideStep4: "按下按键进行记录", guideRowDefault: "点击对应行的输入框", guideNote: "注册后，该按键会被绑定到一个空命令并被禁用。", openSettingsPage: "打开设置页面", close: "关闭", guideTargetFmt: "目标：$label$（$combo$）", guideRowFmt: "点击“屏蔽: $row$”这一行的输入框", bulkLabel: "此标签页：", disableAll: "全部禁用", enableAll: "全部启用", addCustom: "＋ 添加自定义快捷键", disableFmt: "禁用 $name$", noteCommand: "请在右侧的键盘快捷键设置中注册", noteUnblockable: "因浏览器限制无法屏蔽", gearTitle: "在 Chrome 快捷键页面注册", lockTitle: "因浏览器限制无法屏蔽", delete: "删除", statusDisabled: "已禁用 $count$ 个快捷键", statusAllEnabled: "所有快捷键已启用", showReserved: "显示浏览器保留的快捷键" },
  zh_TW: { appDesc: "瀏覽時逐一開啟或關閉鍵盤快速鍵——封鎖誤觸的 Ctrl+W、退格鍵導覽、F12 等。", openShortcutsTitle: "開啟 Chrome 的鍵盤快速鍵頁面", toggleTheme: "切換主題", searchTitle: "搜尋", capturePlaceholder: "例如 Ctrl + K（可直接輸入）", captureTitle: "按下按鍵以記錄", record: "記錄", recording: "記錄中…", labelPlaceholder: "標籤（選填）", add: "新增", cancel: "取消", catAll: "全部", catNav: "導覽", catEdit: "編輯", catTab: "分頁", catDev: "開發", catCustom: "自訂", searchPlaceholder: "搜尋快速鍵", searchAddPlaceholder: "搜尋 / 新增（例如 Ctrl+K）", guideTitle: "如何註冊快速鍵", guideStep1: "點選下方的「開啟設定頁面」", guideStep2: "在清單中找到「Shortcut Blocker」", guideStep4: "按下按鍵進行記錄", guideRowDefault: "點選對應列的輸入框", guideNote: "註冊後，該按鍵會被指派到一個空指令並停用。", openSettingsPage: "開啟設定頁面", close: "關閉", guideTargetFmt: "目標：$label$（$combo$）", guideRowFmt: "點選「封鎖: $row$」這一列的輸入框", bulkLabel: "此分頁：", disableAll: "全部停用", enableAll: "全部啟用", addCustom: "＋ 新增自訂快速鍵", disableFmt: "停用 $name$", noteCommand: "請在右側的鍵盤快速鍵設定中註冊", noteUnblockable: "因瀏覽器限制無法封鎖", gearTitle: "在 Chrome 快速鍵頁面註冊", lockTitle: "因瀏覽器限制無法封鎖", delete: "刪除", statusDisabled: "已停用 $count$ 個快速鍵", statusAllEnabled: "所有快速鍵已啟用", showReserved: "顯示瀏覽器保留的快速鍵" },
  ko: { appDesc: "브라우징 중 키보드 단축키를 개별적으로 켜고 끄세요 — 실수로 누르는 Ctrl+W, 백스페이스 탐색, F12 등을 차단합니다.", openShortcutsTitle: "Chrome 키보드 단축키 페이지 열기", toggleTheme: "테마 전환", searchTitle: "검색", capturePlaceholder: "예: Ctrl + K (직접 입력 가능)", captureTitle: "키를 눌러 기록", record: "기록", recording: "기록 중…", labelPlaceholder: "라벨 (선택)", add: "추가", cancel: "취소", catAll: "전체", catNav: "탐색", catEdit: "편집", catTab: "탭", catDev: "개발", catCustom: "사용자", searchPlaceholder: "단축키 검색", searchAddPlaceholder: "검색 / 추가 (예: Ctrl+K)", guideTitle: "단축키 등록 방법", guideStep1: "아래의 \"설정 페이지 열기\"를 클릭", guideStep2: "목록에서 \"Shortcut Blocker\" 찾기", guideStep4: "키를 실제로 눌러 기록", guideRowDefault: "해당 행의 입력란을 클릭", guideNote: "등록하면 해당 키는 아무 동작도 하지 않는 명령에 할당되어 비활성화됩니다.", openSettingsPage: "설정 페이지 열기", close: "닫기", guideTargetFmt: "대상: $label$ ($combo$)", guideRowFmt: "\"차단: $row$\" 행의 입력란을 클릭", bulkLabel: "이 탭을:", disableAll: "모두 비활성화", enableAll: "모두 활성화", addCustom: "＋ 사용자 단축키 추가", disableFmt: "$name$ 비활성화", noteCommand: "오른쪽 키보드 단축키 설정에서 등록", noteUnblockable: "브라우저 제약으로 차단 불가", gearTitle: "Chrome 단축키 페이지에서 등록", lockTitle: "브라우저 제약으로 차단 불가", delete: "삭제", statusDisabled: "$count$개의 단축키 비활성화됨", statusAllEnabled: "모든 단축키 활성화됨", showReserved: "브라우저 예약 단축키 표시" },
};

const PH = {
  guideTargetFmt: { label: { content: "$1" }, combo: { content: "$2" } },
  guideRowFmt: { row: { content: "$1" } },
  disableFmt: { name: { content: "$1" } },
  statusDisabled: { count: { content: "$1" } },
};

for (const lang of Object.keys(UI)) {
  const out = { appName: { message: BRAND } };
  for (const [k, v] of Object.entries(UI[lang])) {
    out[k] = { message: v };
    if (PH[k]) out[k].placeholders = PH[k];
  }
  for (const [k, v] of Object.entries(LABELS[lang])) {
    out["sc_" + k] = { message: v };
  }
  for (const [cmdId, labelKey] of Object.entries(CMD2LABEL)) {
    const desc = `${blockPrefix[lang]}: ${LABELS[lang][labelKey]} (${COMBOS[cmdId]})`;
    out["cmd_" + cmdId.replace(/-/g, "_")] = { message: desc };
  }
  const dir = path.join(ROOT, "_locales", lang);
  fs.mkdirSync(dir, { recursive: true });
  fs.writeFileSync(path.join(dir, "messages.json"), JSON.stringify(out, null, 2) + "\n");
}
console.log("locales:", Object.keys(UI).join(", "));
